# Generated by Django 2.0.dev20170705064109 on 2017-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
