# Generated by Django 2.0.dev20170705064109 on 2017-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
